import type { Metadata } from "next";
import { inter } from "./ui/fonts"

import "./globals.css";

// Components
import Navigation from "./ui/common/navigation"

export const metadata: Metadata = {
  title: "Lineup Manager",
  description: "Roller derby lineup manager. Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Navigation />
        <div className="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
          {children}
        </div>
      </body>
    </html>
  );
}
